/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CommentUpdateManyWithoutDogParksInput } from "./CommentUpdateManyWithoutDogParksInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsNumber,
  Max,
} from "class-validator";
import { Type } from "class-transformer";
import { ReviewUpdateManyWithoutDogParksInput } from "./ReviewUpdateManyWithoutDogParksInput";

@InputType()
class DogParkUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CommentUpdateManyWithoutDogParksInput,
  })
  @ValidateNested()
  @Type(() => CommentUpdateManyWithoutDogParksInput)
  @IsOptional()
  @Field(() => CommentUpdateManyWithoutDogParksInput, {
    nullable: true,
  })
  comments?: CommentUpdateManyWithoutDogParksInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  lat?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  lng?: number;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: () => ReviewUpdateManyWithoutDogParksInput,
  })
  @ValidateNested()
  @Type(() => ReviewUpdateManyWithoutDogParksInput)
  @IsOptional()
  @Field(() => ReviewUpdateManyWithoutDogParksInput, {
    nullable: true,
  })
  reviews?: ReviewUpdateManyWithoutDogParksInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  size?: string;
}

export { DogParkUpdateInput as DogParkUpdateInput };
